### ISSUE TITLE
Scaling: be able to handle a few simultaneous users

### ISSUE THREAD

**Issue by eugenecormier** [trevordixon/LilyBin#34]
I'll put this out there again because of the flurry of new activity. It would be really nice to have the actual score compile to happen on a users machine, not the server. Better for lilybin.com (less CPU cycles) and better for users (faster). It would also deal with the scaleability problems we saw last year when I had a class of 50 trying to all click preview at the same time and having everything melt down

**Comment by TimothyGu** [comment]
That's kinda hard to do. The only way to do that with lilypond is through probably Emscripten. And LilyPond has an especially complex build system with lots of even more difficult dependencies like TeX and Guile.

**Comment by eugenecormier** [comment]
Yeah, I figured. I'm just mentioning it because lilybin _does_ have a scalability problem, we do have a way to test before it becomes a problem (let's keep our fingers crossed that it does in fact become a problem :)

**Comment by trevordixon** [comment]
I think your best option is to launch a bunch of instances of LilyBin in somebody's cloud and direct your students to use those.

**Comment by eugenecormier** [comment]
I can do that at the university, for sure.... the only reason I mention it is because if lilybin gets a growing userbase, it's going to have issues. How will you fix that then? mirrors maybe?

**Comment by trevordixon** [comment]
So far, it's only ever been a problem during your class. If server strain starts to happen more frequently, I have some ideas for handling the load.

**Comment by trevordixon** [comment]
It might be possible to compile LilyPond for NaCl to run in Chrome. That would be a cool project for somebody take on. Port LilyPond to NaCl.

**Comment by trevordixon** [comment]
Another potential inexpensive solution to the scaling issue is to run LilyPond in AWS Lambda. https://aws.amazon.com/blogs/compute/running-executables-in-aws-lambda/

**Comment by trevordixon** [comment]
We could compile in AWS Lambda and easily stay well within the free usage tier. [AWS Lambda pricing](http://aws.amazon.com/lambda/pricing/). With 1 GB of memory, we'd get 400,000 free seconds of computing. If every compilation took 30 seconds (way generous), we'd get ~13,000 free compilations—way more than needed. If this ever becomes an issue again, this'll be the way to go. While we're at it, we could store scores in DynamoDB and serve the front end from S3, all for less than a dollar a month I estimate.

**Comment by TimothyGu** [comment]
I just signed up for an AWS account. I'll play around with Lambda for a few days and let's see how well this thing works :)

I'm having some second thoughts about using DynamoDB, since it is not open source and who knows what would happen if say their servers crashed. Having a VPS is also more hackable than on a PaaS service like S3.

**Comment by scottlinux** [comment]
DynamoDB is very much temporary. Good for things like sessions, or meta data but not much else. There are size limits to what it can store as well. I'm not a fan of DynamoDB.

**Comment by TimothyGu** [comment]
Seems like I have to use S3 for storage of the generated PNGs and PDFs. That kind of sucks.

**Comment by TimothyGu** [comment]
Prototype for the AWS Lambda slave done: https://github.com/TimothyGu/lilybin-slave

Basically it does a few things:

- takes in a key to store the files in S3 and the lilypond code
- installs lilypond
- compiles the code
- upload the produced files into S3 with the specific key.

Lambda doesn't have a way to transmit large binary files, only JSON result can be returned.

A separate step to install lilypond is needed, because installed copy is too big for Lambda's code size restriction (it ended up being about 32 MB, out of 20 MB). With the vanilla install script it works (even though it's around 22 MB but the system still accepted it), but because the Lambda machines are so slow it takes about 15 seconds to decompress and install it. So I decided to just decompress it before hand and upload it to a S3 bucket that is downloaded on-the-fly.

All work is done in `/tmp` as that's the only writable directory in the entire system.

There is also a very nasty bug with lilypond and ghostscript:

https://github.com/TimothyGu/lilybin-slave/blob/master/install-lilypond.sh#L8-L15

The workaround is taken from: https://lists.fedoraproject.org/pipermail/test/2010-September/093529.html



BTW, a small benchmark with the default boilerplate score:

Initialize: 0.8 s
Installation: 2.8 s (with the official installation script it's about 15 s)
Compilation: 4.7 s
Upload: 0.1 s
Total/Billed: 7.8 s

This was on a 512 MB box, peak memory used is 260 MB.

No, the performance is not impressive at all (currently a `prepare_preview` request only takes less than 2 seconds), although it might be faster than the current architecture once the number of simultaneous users reaches a specific threshold. Nevertheless, I would say that AWS Lambda is probably not the best choice for this kind of workflow, even though it scales well.

**Comment by trevordixon** [comment]
Thanks for looking into that! The most worrisome figure is the 4.7s for actual compilation. Initialization and installation might not matter so much, depending on how the containers get reused in real life usage.

According to https://alestic.com/2014/11/aws-lambda-speed/, execution time may improve if you give it more memory. Can you try it with max memory?

**Comment by TimothyGu** [comment]
With max memory (1024 MB):

Init: 0.5 s
Installation: 1.9 s
Compilation: 4.5 s
Upload: 0.0 s
Total: 6.6 s
Max memory: 300 MB

The installation time is cut down significantly, but unfortunately not the actual compilation.

**Comment by trevordixon** [comment]
Thanks again. We'll think about this more when load becomes an issue.

**Comment by TimothyGu** [comment]
Also, Lambda seems to cache the container sometimes, so a realistic compile would take less than 5 seconds:

> **Q: Will AWS Lambda reuse function instances?**
>
> To improve performance, AWS Lambda may choose to retain an instance of your function and reuse it to serve a subsequent request, rather than creating a new copy. Your code should not assume that this will always happen.
>
> (From http://aws.amazon.com/lambda/faqs/)

**Comment by trevordixon** [comment]
Try skipping the install step in case LilyPond is already there, then see what kind of total turnaround time you get after the initial request.

**Comment by TimothyGu** [comment]
@trevordixon yep I did that, and a two-page document now only needs 4.8 seconds to render.

**Comment by trevordixon** [comment]
And the same score takes ~2 seconds currently?

**Comment by TimothyGu** [comment]
Hm, while a simple score only takes ~2 seconds currently (and ~4 on Lambda), a more complex score that takes 3.7 currently takes only ~4.8 s on lambda. I guess doing this is worthwhile then.

**Comment by TimothyGu** [comment]
Hm, when I test it again *now*, the simple score only takes 2.5 seconds with a pre-heated machine.

**Comment by trevordixon** [comment]
@eugenecormier Done by @TimothyGu. Should be able to handle your whole class and more now! Give us a report next time you get to try it.

**Comment by EuAndreh** [comment]
W00t, awesome job!
