### ISSUE TITLE
Fonts used for pdf.js toolbar buttons do not load in Firefox

### ISSUE THREAD

**Issue by PaulMorris** [trevordixon/LilyBin#81]
The buttons still work, but you can't tell them apart visually.  The console indicates a cross-origin problem:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/fonts/glyphicons-halflings-regular.woff2. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘(null)’).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/fonts/glyphicons-halflings-regular.woff. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘(null)’).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/fonts/glyphicons-halflings-regular.ttf. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘(null)’).
```

**Comment by TimothyGu** [comment]
Seems to be working here:

![image](https://cloud.githubusercontent.com/assets/1538624/25599967/19be4ae0-2e95-11e7-89c2-b406ac0100cf.png)

There aren't any messages on the console either.

**Comment by PaulMorris** [comment]
Hmm, I'm on Ubuntu 16.04. I checked on a friend's mac and everything was fine there.  So maybe it's only on Ubuntu?  (Like maybe that font isn't installed, so it tries to access them from a cdn instead?)

![lilybin-firefox-pdfjs-font-glypths-2](https://cloud.githubusercontent.com/assets/1091693/25603744/577b900e-2ecc-11e7-8083-9341a00f6cfb.png)

**Comment by TimothyGu** [comment]
Hmm... tried on Debian testing with both Firefox ESR and Beta and they both seem to work...

![screenshot from 2017-05-01 21-43-17](https://cloud.githubusercontent.com/assets/1538624/25604280/3801b16e-2eb7-11e7-8955-ece8445d19e5.png)
![screenshot from 2017-05-01 21-41-39](https://cloud.githubusercontent.com/assets/1538624/25604281/380ed6be-2eb7-11e7-9c82-242b31ae25c3.png)

Can you check the response headers with Firefox Developer Tools to make sure `Access-Control-Allow-Origin` is set correctly? The `(null)` bit in your log kind of makes me wonder how you are trying to access Lilybin, through Lilybin.com or otherwise... Also what version of Firefox are you using?

![screenshot from 2017-05-01 21-47-07](https://cloud.githubusercontent.com/assets/1538624/25604378/dc894698-2eb7-11e7-8106-ff752c20ccf9.png)

**Comment by PaulMorris** [comment]
I'm on FF 54.0b1 (beta).  I tried it with a clean FF profile with no add-ons installed and it worked fine.  I think some add-on that I have installed that blocks trackers is causing the problem. (By say setting the origin to 'null' which causes those `Access-Control-Allow-Origin` errors?)  So, um, sorry for the noise!  Feel free to close this.

**Comment by TimothyGu** [comment]
Thanks!
